---

workspace:
  base: /go
  path: src/github.com/packethost/cacher

pipeline:
  lint:
    group: ci
    image: golangci/golangci-lint:v1.23.8
    commands:
      - golangci-lint run -v -D errcheck

  fmt:
    group: ci
    image: golang:1.13-alpine
    commands:
      - apk add --update --upgrade --no-cache git
      - go get golang.org/x/tools/cmd/goimports
      - goimports -d . | (! grep .)

  test:
    group: ci
    image: golang:1.13-alpine
    commands:
      - CGO_ENABLED=0 go test -v ./...

  build:
    group: ci
    image: golang:1.13-alpine
    commands:
      - CGO_ENABLED=0 go build -ldflags="-X main.gitRev=${DRONE_COMMIT_SHA}" -o cacher-linux-x86_64

  publish:
    group: publish
    image: plugins/docker
    registry: quay.io
    repo: quay.io/packet/cacher
    tags:
      - ${DRONE_BRANCH/\//-}
      - ${DRONE_BUILD_NUMBER}-${DRONE_COMMIT_SHA}
    when:
      event: push
    secrets:
      - docker_password
      - docker_username
