---
version: '2.1'
services:
  server:
    build: .
    environment:
      CACHER_FETCH_PER_PAGE: ${CACHER_FETCH_PER_PAGE}
      FACILITY: ${FACILITY:-lab1}
      PACKET_API_AUTH_TOKEN: ${PACKET_API_AUTH_TOKEN}
      PACKET_API_URL: ${PACKET_API_URL:-https://lab-api.packet.net}
      PACKET_CONSUMER_TOKEN: ${PACKET_CONSUMER_TOKEN}
      PACKET_ENV: testing
      PACKET_VERSION: 42
      ROLLBAR_TOKEN: 42
    volumes:
      - ./certs:/certs

